import Foundation

struct MarkdownExporter {
    static func generateMarkdown(from observation: Observation) -> String {
        var md = "# \(observation.title)\n\n"
        md += "**Date:** \(observation.date.formatted(.dateTime.year().month().day()))\n\n"
        md += "**Target:** \(observation.targetName)\n\n"
        md += "**Exposure:** \(observation.exposureInfo)\n\n"
        md += "**Stacking Method:** \(observation.stackingMethod)\n\n"

        md += "## Equipment\n"
        md += "- Telescope: \(observation.equipment.telescope)\n"
        md += "- Mount: \(observation.equipment.mount)\n"
        md += "- Camera: \(observation.equipment.camera)\n"
        md += "- Filters: \(observation.equipment.filters)\n\n"

        md += "## Location\n"
        md += "- Name: \(observation.location.name)\n"
        md += "- Latitude: \(observation.location.latitude)\n"
        md += "- Longitude: \(observation.location.longitude)\n\n"

        if !observation.notes.isEmpty {
            md += "## Notes\n"
            md += observation.notes + "\n\n"
        }

        md += "_Generated by SkyJournal_"
        return md
    }
}

